[package]
name = "app"
version = "0.2.4"
edition = "2021"
build = "build.rs"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[lints]
workspace = true

[build-dependencies]
tauri-build = { version = "2.5", features = [] }

[dependencies]
tauri = { version = "2.11", features = ["custom-protocol"] }
core-ssh.path = "../core-ssh"
core-tunnel.path = "../core-tunnel"
core-sftp = { version = "0.1.0", path = "../core-sftp" }
core-monitor = { version = "0.1.0", path = "../core-monitor" }
core-store.path = "../core-store"
core-policy.path = "../core-policy"
tokio.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
parking_lot.workspace = true
zeroize = { version = "1", features = ["zeroize_derive"] }
base64 = "0.22.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
tauri-plugin-clipboard-manager = "2.3.2"
tauri-plugin-updater = "2.10.1"
