[package]
name = "core-tunnel"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
core-ssh.path = "../core-ssh"
tokio.workspace = true
bytes.workspace = true
thiserror.workspace = true
tracing.workspace = true
parking_lot.workspace = true
russh.workspace = true
socket2 = "0.5"

[dev-dependencies]
anyhow.workspace = true
rand = "0.10"
