// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 前端传入的认证材料（secret 只在内存停留，Zeroizing 落 core-ssh）
 */
export type AuthSpec = { "type": "password", password: string, } | { "type": "publicKey", keyPem: string, passphrase?: string | null, } | { "type": "keyboardInteractive" } | { "type": "agent" };
