// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 目录任务失败条目（TransferJobView.failedEntries[]）
 */
export type FailedEntry = { path: string, error: string, };
