// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SFTP/本地目录条目（sftp_list/local_list 帧元素）
 */
export type FileEntry = { name: string, path: string, kind: 'file' | 'dir' | 'symlink' | 'other', size: number, 
/**
 * 本地列表无此键
 */
permissions?: number | null, mtime?: number, user?: string | null, group?: string | null, };
