// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostKeyPromptFrame = { v: 1, type: 'hostkey_prompt', confirmId: string, kind: 'unknown' | 'changed', host: string, port: number, keyType: string, fingerprint?: string | null, oldFingerprint?: string | null, newFingerprint?: string | null, };
