// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthSpec } from "./AuthSpec";

/**
 * 一跳跳板（已解析的认证材料；由 sessions.rs 从档案+保险库解析注入）
 */
export type JumpHopSpec = { host: string, port: number, user: string, auth: AuthSpec, };
