// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KiPrompt } from "./KiPrompt";

export type KiChallengeFrame = { v: 1, type: 'ki_challenge', confirmId: string, name: string, instruction: string, prompts: Array<KiPrompt>, };
