// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * KI 挑战的单条提示（KiChallengeFrame.prompts[]）
 */
export type KiPrompt = { prompt: string, echo: boolean, };
