// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 登录宏被后端跳过的告知帧（v1 唯一 reason：su 手输密码，应答时机不可知）
 */
export type MacroSkippedFrame = { v: 1, type: 'macro_skipped', tabId: string, reason: 'suManualPassword', };
