// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetricsSnapshot = { 
/**
 * 采集完成的本地时间（epoch ms）。
 */
tsMs: number, 
/**
 * 与上一轮的实测间隔（首轮 0）。
 */
intervalMs: number, 
/**
 * CPU 忙率 0..100（首轮 None，需两轮差分）。
 */
cpuBusyPct: number | null, load: [number, number, number], procsRunning: number, procsTotal: number, memTotalKb: number, memAvailKb: number, swapTotalKb: number, swapFreeKb: number, disks: Array<{ name: string, 
/**
 * 首轮 None；此后为 B/s（sector=512B 差分换算）。
 */
readBps: number | null, writeBps: number | null, }>, nets: Array<{ iface: string, rxBps: number | null, txBps: number | null, }>, 
/**
 * CPU 占用 Top（ps 口径为进程存活期平均）。
 */
procs: Array<{ pid: number, rssKb: number, cpuPct: number, memPct: number, comm: string, }>, };
