// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsSnapshot } from "./MetricsSnapshot";

/**
 * metrics_subscribe 推送帧
 */
export type MetricsEvent = { "kind": "snapshot", data: MetricsSnapshot, } | { "kind": "error", message: string, fatal: boolean, };
