// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §9.6 随会话隧道启动结果（session_tunnels 帧 results[]）
 */
export type SessionTunnelResult = { id: string, name: string, bind: string, ok: boolean, error: string | null, };
