// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionStateFrame = { v: 1, type: 'session_state', tabId: string, state: 'connected' | 'closed' | 'reconnecting' | 'error', message?: string | null, attempt?: number | null, reconnected?: boolean | null, 
/**
 * local 会话连接成功帧：'local' + 实际启动的 shell 程序名
 */
kind?: 'local', shell?: string | null, 
/**
 * 首次连接成功帧携带的远端标识
 */
host?: string | null, port?: number | null, user?: string | null, };
