// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 会话类型：ssh = 远程 SSH；local = 本机 PTY（ConPTY），host/port/username/auth_type 存占位值
 */
export type SessionKind = "ssh" | "local";
