// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthType } from "./AuthType";
import type { SessionKind } from "./SessionKind";

export type SessionRecord = { id: string, name: string, 
/**
 * 会话类型（旧导出包络无此字段，默认 ssh）
 */
kind: SessionKind, host: string, port: number, username: string, authType: AuthType, keyPath?: string | null, 
/**
 * local：启动的 shell（powershell|pwsh|cmd 或自定义路径）；None = 自动（pwsh→powershell→cmd）
 */
shell?: string | null, 
/**
 * local：启动目录；None = 用户主目录
 */
workdir?: string | null, 
/**
 * ProxyJump 链：session id 数组（就近→最远）；空 = 直连
 */
jumpChain: Array<string>, groupPath: string, 
/**
 * 侧栏色点（hex，如 '#e5484d'）；None = 无色
 */
color?: string | null, 
/**
 * 终端编码（encoding_rs 标签；'utf-8' = 直通不转码）。旧导出包络无此字段，默认 utf-8
 */
encoding: string, 
/**
 * 登录后切换用户（su）的目标用户名；None/空 = 不切换。密码存 credentials(kind=su_password)
 */
suUser?: string | null, 
/**
 * 登录宏：进 shell 后自动逐行执行的命令序列（纯文本，非秘密）；None/空 = 不执行。
 * 语义：无 su 即发；有 su 则密码应答后发；重连重放（.scratch/login-macro/spec.md）
 */
loginMacro?: string | null, 
/**
 * MCP 工具权限覆盖（稀疏映射，键 = 分组名 list_sessions/ssh_exec/sftp_read/
 * sftp_write/sftp_transfer）；缺省空 = 全部跟随全局 mcp.allow.* 设置
 */
mcpPerms: Record<string, boolean>, tags: Array<string>, command?: string | null, createdAt: string, updatedAt: string, };
