// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthSpec } from "./AuthSpec";
import type { JumpHopSpec } from "./JumpHopSpec";

export type TermOpenSpec = { host: string, port: number, user: string, auth: AuthSpec, 
/**
 * ProxyJump 链（就近→最远）；空 = 直连
 */
jumpChain: Array<JumpHopSpec>, 
/**
 * 终端类型，默认 xterm-256color
 */
term?: string | null, 
/**
 * 启动命令；None = 登录 shell
 */
command?: string | null, 
/**
 * 终端编码（encoding_rs 标签）；默认 utf-8 = 直通不转码
 */
encoding: string, 
/**
 * 登录后切换用户（su）目标用户名；None/空 = 不切换（批次二十二）
 */
suUser?: string | null, 
/**
 * su 密码（内存经手即弃；档案路径由 resolve 从保险库读出）
 */
suPassword?: string | null, 
/**
 * 登录宏：进 shell 后自动逐行执行的命令（多行文本）；None/空 = 不执行。
 * 语义：无 su 即发；有 su 则密码应答后发；配 command 的会话不执行；重连重放
 */
loginMacro?: string | null, };
