// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthType } from "./AuthType";

/**
 * 连通性测试入参（秘密材料只在内存经手；authType 与 SessionRecord 同 serde 形式）
 */
export type TestConnectRequest = { 
/**
 * 关联会话（保险库回退 + 审计归属）；可空 = 表单草稿未保存
 */
sessionId?: string | null, host: string, port: number, user: string, authType: AuthType, password?: string | null, keyPath?: string | null, passphrase?: string | null, 
/**
 * 跳板会话 id 链（就近→最远）；空 = 直连
 */
jumpChain: Array<string>, };
