// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailedEntry } from "./FailedEntry";

/**
 * 目录任务视图（transfer_subscribe 帧 jobs[] / transfer_job_list）
 */
export type TransferJobView = { id: string, direction: 'upload' | 'download', summary: string, state: 'scanning' | 'transferring' | 'finalizing' | 'completed' | 'failed' | 'canceled', paused: boolean, scanDone: boolean, discoveredFiles: number, discoveredBytes: number, completedFiles: number, failedFiles: number, skipped: number, bytesDone: number, error: string | null, current: Array<string>, failedEntries: Array<FailedEntry>, rate: number, };
