// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单文件传输视图（transfer_subscribe/transfer_list 帧元素）
 */
export type TransferView = { id: string, direction: 'upload' | 'download', local: string, remote: string, state: 'queued' | 'running' | 'paused' | 'done' | 'failed' | 'canceled', bytesDone: number, bytesTotal: number, retries: number, 
/**
 * 历史回放行无此键
 */
priority?: boolean | null, 
/**
 * 历史回放行无此键
 */
onExists?: 'resume' | 'overwrite' | 'skip' | 'rename', error: string | null, 
/**
 * 仅订阅帧注入（差分速率）；list 帧无此键
 */
rate?: number, 
/**
 * true = 历史回放行（上次运行终态）
 */
history?: boolean | null, };
