// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransferHistoryView = { id: string, sessionId: string, direction: 'upload' | 'download', local: string, remote: string, bytesDone: number, bytesTotal: number, state: 'queued' | 'running' | 'paused' | 'done' | 'failed' | 'canceled', error: string | null, updatedAt: string, };
