// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 运行中隧道视图（tunnel_subscribe 帧元素；TS 名 TunnelInfo）。
 * sessionId：卡 6 起运行条目自持会话归属——此前线面缺这字段，前端只能靠定义反查归属。
 */
export type TunnelInfo = { tunnelId: string, kind: 'local' | 'remote' | 'dynamic', bind: string, target: string | null, status: 'starting' | 'listening' | 'reconnecting' | 'stopped' | 'failed', activeConns: number, totalConns: number, bytesUp: number, bytesDown: number, rateUp: number, rateDown: number, errors: number, rejectedConns: number, reconnects: number, lastError: string | null, 
/**
 * 归属会话（空串 = 独立隧道，不参与会话失效扇出）
 */
sessionId: string, };
