// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TunnelRecord = { id: string, sessionId: string, kind: 'local' | 'remote' | 'dynamic', 
/**
 * 显示名（模板预填；可空 → 面板回退为绑定地址）
 */
name: string, bindHost: string, bindPort: number, targetHost?: string | null, targetPort?: number | null, 
/**
 * 开机自启（app 启动即建立）
 */
autostart: boolean, 
/**
 * 随会话自动建立（该会话终端连接成功后拉起）
 */
withSession: boolean, createdAt: string, };
