[package]
name = "core-sftp"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lints]
workspace = true

[dependencies]
core-policy.path = "../core-policy"
core-ssh.path = "../core-ssh"
tokio.workspace = true
bytes.workspace = true
thiserror.workspace = true
tracing.workspace = true
russh-sftp = "2.4.0"
serde.workspace = true

[dev-dependencies]
core-policy.path = "../core-policy"
parking_lot.workspace = true
serde_json.workspace = true
rand = "0.10.2"
russh.workspace = true
tokio.workspace = true
zeroize = "1"
